## 1 Electricity Production

In [1]:
import cvxpy as cp

x = cp.Variable(2, nonneg  = True) # vector variable

constraints = []
constraints.append((2/3)*x[0]+x[1]<=18)
constraints.append(2*x[0]+x[1]>=8)
constraints.append(x[0]<=12)
constraints.append(x[1]<=16)

obj_func=x[0]+x[1]

problem = cp.Problem(cp.Maximize(obj_func), constraints)

#problem.solve(verbose = True)
#problem.solve(solver=cp.CVXOPT,verbose = True) #verbose parameter determines showing/not showing the output
problem.solve(solver=cp.GUROBI,verbose = True)

print("obj_func =")
print(obj_func.value)
print("x =")
print(x.value)

                                     CVXPY                                     
                                     v1.2.1                                    
(CVXPY) Aug 30 11:45:47 AM: Your problem has 2 variables, 4 constraints, and 0 parameters.
(CVXPY) Aug 30 11:45:47 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Aug 30 11:45:47 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Aug 30 11:45:47 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Aug 30 11:45:47 AM: Compiling problem (target solver=GUROBI).
(CVXPY) Aug 30 11:45:47 AM: Reduction chain: FlipObjective -> CvxAttr2Constr -> Qp2SymbolicQp -

## 2 High Tech Inc.

In [2]:
import cvxpy as cp

x = cp.Variable(2, nonneg  = True) # vector variable

obj_func=20*x[0]+30*x[1]

constraints = []
constraints.append(x[0]>=25)
constraints.append(4*x[0]+3*x[1]<=240)
constraints.append(x[0]+2*x[1]<=140)

problem = cp.Problem(cp.Maximize(obj_func), constraints)

#problem.solve(solver=cp.CVXOPT,verbose = True) #verbose parameter determines showing/not showing the output
problem.solve(solver=cp.GUROBI,verbose = True)

print("obj_func =")
print(obj_func.value)
print("x =")
print(x.value)


                                     CVXPY                                     
                                     v1.2.1                                    
(CVXPY) Aug 30 11:48:19 AM: Your problem has 2 variables, 3 constraints, and 0 parameters.
(CVXPY) Aug 30 11:48:19 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Aug 30 11:48:19 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Aug 30 11:48:19 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Aug 30 11:48:19 AM: Compiling problem (target solver=GUROBI).
(CVXPY) Aug 30 11:48:19 AM: Reduction chain: FlipObjective -> CvxAttr2Constr -> Qp2SymbolicQp -

## 3 Transportation

In [3]:
import cvxpy as cp
import numpy as np


X = cp.Variable((3, 4), nonneg  = True)
m,n=X.shape

C=np.array([[7,3,8,4],[9,5,6,3],[4,6,9,6]]) # unit shipping costs  (3*4 matrix)
W=np.array([[6000],[9000],[4000]])          # warehouse availabiliy (column vector)
R=np.array([[3900,5200,2700,6400]])         # retail outlet demand (row vector)

obj_func=cp.trace(C.T @ X)  #.T takes transpose of a matrix, @ represents matrix product, trace sums the diagonal elements

#%% 1. Inputing constraints using two for loops for columns and rows

constraints = []
for j in range(n):
    constraints.append(cp.sum(X[:,j], axis=0, keepdims=True)==R[0,j]) # axis=0 sums over rows for each column j

for i in range(m):
    constraints.append(cp.sum(X[i,:])<=W[i]) # axis=1 sums over columns for each row i
    #constraints.append(X[i,0]+X[i,1]+X[i,2]+X[i,3]<=W[i])
    
problem = cp.Problem(cp.Minimize(obj_func), constraints)

#problem.solve(solver=cp.CVXOPT,verbose = True)
problem.solve(solver=cp.GUROBI,verbose = True)

print("obj_func =")
print(obj_func.value)
print("X =")
print(np.round(X.value)) 
    
#%% 2. Inputing constraints using vector operation

constraints = []
col_sums = cp.sum(X, axis=0, keepdims=True) # axis=0 sums over rows for each column
constraints.append(col_sums==R)
row_sums = cp.sum(X, axis=1, keepdims=True) # axis=1 sums over columns for each row
constraints.append(row_sums<=W)

problem = cp.Problem(cp.Minimize(obj_func), constraints)

#problem.solve(solver=cp.CVXOPT,verbose = True)
problem.solve(solver=cp.GUROBI,verbose = True)

print("obj_func =")
print(obj_func.value)
print("X =")
print(X.value)


                                     CVXPY                                     
                                     v1.2.1                                    
(CVXPY) Aug 30 11:49:45 AM: Your problem has 12 variables, 7 constraints, and 0 parameters.
(CVXPY) Aug 30 11:49:45 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Aug 30 11:49:45 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Aug 30 11:49:45 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Aug 30 11:49:45 AM: Compiling problem (target solver=GUROBI).
(CVXPY) Aug 30 11:49:45 AM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffi

## 4 Product Blend

In [5]:
import cvxpy as cp


X = cp.Variable((2, 2), nonneg  = True)
#m,n=X.shape


obj_func=15*X[0,0]+20*X[0,1]+11*X[1,0]+16*X[1,1]


constraints = []
constraints.append(-X[0,0]+9*X[1,0]>=0)
constraints.append(-7*X[0,1]+3*X[1,1]>=0)
constraints.append(X[0,0]+X[1,0]>=60000)
constraints.append(X[0,1]+X[1,1]>=15000)
constraints.append(X[0,0]+X[1,0]<=80000)
constraints.append(X[0,1]+X[1,1]<=40000)
constraints.append(X[0,0]+X[0,1]<=70000)
constraints.append(X[1,0]+X[1,1]<=60000)


problem = cp.Problem(cp.Maximize(obj_func), constraints)

#problem.solve(solver=cp.CVXOPT,verbose = True) #verbose parameter determines showing/not showing the output
problem.solve(solver=cp.GUROBI,verbose = True)

print("obj_func =")
print(obj_func.value)
print("X =")
print(X.value)


                                     CVXPY                                     
                                     v1.2.1                                    
(CVXPY) Aug 30 11:51:01 AM: Your problem has 4 variables, 8 constraints, and 0 parameters.
(CVXPY) Aug 30 11:51:01 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Aug 30 11:51:01 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Aug 30 11:51:01 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Aug 30 11:51:01 AM: Compiling problem (target solver=GUROBI).
(CVXPY) Aug 30 11:51:01 AM: Reduction chain: FlipObjective -> CvxAttr2Constr -> Qp2SymbolicQp -

## 5 Production Schedule

In [7]:
import cvxpy as cp


x = cp.Variable(4, nonneg  = True) # vector variable
y = cp.Variable(2, nonneg  = True) # vector variable
w = cp.Variable(3, nonneg  = True) # vector variable


obj_func=12*x[0]+12*x[1]+14*x[2]+14*x[3]+16*y[0]+16*y[1]+3*(w[0]+w[1]+w[2])


constraints = []
constraints.append(x[0]-w[0]==400)
constraints.append(x[1]+y[0]+w[0]-w[1]==750)
constraints.append(x[2]+y[1]+w[1]-w[2]==950)
constraints.append(x[3]+w[2]==700)  # to fix infeasibility change 900 to 700
constraints.append(x[0]<=800)
constraints.append(x[1]<=800)
constraints.append(x[2]<=800)
constraints.append(x[3]<=800)
constraints.append(y[0]<=200)
constraints.append(y[1]<=200)
constraints.append(w[0]<=50)
constraints.append(w[1]<=50)
constraints.append(w[2]<=50)



problem = cp.Problem(cp.Minimize(obj_func), constraints)

#problem.solve(solver=cp.CVXOPT,verbose = True)
#problem.solve(verbose = True)
problem.solve(solver=cp.GUROBI,verbose = False)

print("obj_func =")
print(obj_func.value)
print("x =")
print(x.value)
print("y =")
print(y.value)
print("w =")
print(w.value)


obj_func =
37150.0
x =
[400. 800. 800. 700.]
y =
[  0. 100.]
w =
[ 0. 50.  0.]


## 6 Investment

In [10]:
import cvxpy as cp

x = cp.Variable(5, nonneg  = True) # vector variable
s = cp.Variable(3, nonneg  = True) # vector variable

obj_func=x[1]+1.9*x[3]+1.5*x[4]+1.08*s[2]

constraints = []
constraints.append(x[0]+x[2]+x[3]+s[0]==100000)
constraints.append(0.5*x[0]-x[1]+1.2*x[2]+1.08*s[0]-s[1]==0)
constraints.append(x[0]+0.5*x[1]-x[4]+1.08*s[1]-s[2]==0)
constraints.append(x[0]<=75000)
constraints.append(x[1]<=75000)
constraints.append(x[2]<=75000)
constraints.append(x[3]<=75000)
constraints.append(x[4]<=75000)


problem = cp.Problem(cp.Maximize(obj_func), constraints)

#problem.solve(solver=cp.CVXOPT,verbose = True)
problem.solve(solver=cp.GUROBI,verbose = True)

print("obj_func =")
print(obj_func.value)
print("x =")
print(x.value)
print("s =")
print(s.value)

                                     CVXPY                                     
                                     v1.2.1                                    
(CVXPY) Aug 30 11:53:43 AM: Your problem has 8 variables, 8 constraints, and 0 parameters.
(CVXPY) Aug 30 11:53:43 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Aug 30 11:53:43 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Aug 30 11:53:43 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Aug 30 11:53:43 AM: Compiling problem (target solver=GUROBI).
(CVXPY) Aug 30 11:53:43 AM: Reduction chain: FlipObjective -> CvxAttr2Constr -> Qp2SymbolicQp -

## 7 LP Example with Unique Optimal Solution

In [11]:
import cvxpy as cp


x = cp.Variable(2, nonneg  = True) # vector variable


obj_func=2*x[0]+3*x[1]
#obj_func_neg=-2*x[0]-3*x[1]

constraints = []
constraints.append(x[0]-2*x[1]<=4)
constraints.append(2*x[0]+x[1]<=18)
constraints.append(x[1]<=10)


problem = cp.Problem(cp.Maximize(obj_func), constraints)
#problem = cp.Problem(cp.Minimize(obj_func_neg), constraints)

#problem.solve(solver=cp.CVXOPT,verbose = True)
#problem.solve(verbose = True)
problem.solve(solver=cp.GUROBI,verbose = True)

print("obj_func =")
print(obj_func.value)
#print(obj_func_neg.value)
print("x =")
print(x.value)



                                     CVXPY                                     
                                     v1.2.1                                    
(CVXPY) Aug 30 11:54:29 AM: Your problem has 2 variables, 3 constraints, and 0 parameters.
(CVXPY) Aug 30 11:54:29 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Aug 30 11:54:29 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Aug 30 11:54:29 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Aug 30 11:54:29 AM: Compiling problem (target solver=GUROBI).
(CVXPY) Aug 30 11:54:29 AM: Reduction chain: FlipObjective -> CvxAttr2Constr -> Qp2SymbolicQp -

## 8 LP Example with Unique Optimal Solution

In [13]:
import cvxpy as cp


x = cp.Variable(2, nonneg  = True) # vector variable


obj_func=3*x[0]+2*x[1]

constraints = []
constraints.append(2*x[0]+x[1]<=100)
constraints.append(x[0]+x[1]<=80)
constraints.append(x[0]<=40)


problem = cp.Problem(cp.Maximize(obj_func), constraints)

#problem.solve(solver=cp.CVXOPT,verbose = True)
#problem.solve(verbose = True)
problem.solve(solver=cp.GUROBI,verbose = False)

print("obj_func =")
print(obj_func.value)
print("x =")
print(x.value)


obj_func =
180.0
x =
[20. 60.]


## 9 LP Unbounded Example

In [14]:
import cvxpy as cp


x = cp.Variable(2, nonneg  = True) # vector variable


obj_func=x[0]+3*x[1]

constraints = []
constraints.append(x[0]-2*x[1]<=4)
constraints.append(-x[0]+x[1]<=3)
constraints.append(x[1]>=2)


problem = cp.Problem(cp.Maximize(obj_func), constraints)
#problem = cp.Problem(cp.Minimize(obj_func), constraints)

#problem.solve(solver=cp.CVXOPT,verbose = True)
#problem.solve(verbose = True)
problem.solve(solver=cp.GUROBI,verbose = True)

print("obj_func =")
print(obj_func.value)
print("x =")
print(x.value)


                                     CVXPY                                     
                                     v1.2.1                                    
(CVXPY) Aug 30 11:56:14 AM: Your problem has 2 variables, 3 constraints, and 0 parameters.
(CVXPY) Aug 30 11:56:14 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Aug 30 11:56:14 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Aug 30 11:56:14 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Aug 30 11:56:14 AM: Compiling problem (target solver=GUROBI).
(CVXPY) Aug 30 11:56:14 AM: Reduction chain: FlipObjective -> CvxAttr2Constr -> Qp2SymbolicQp -

/Users/samdavanloo/opt/anaconda3/envs/cvxpy_env/lib/python3.10/site-packages/cvxpy/problems/problem.py:1343: UserWarning: 
    The problem is either infeasible or unbounded, but the solver
    cannot tell which. Disable any solver-specific presolve methods
    and re-solve to determine the precise problem status.

    For GUROBI and CPLEX you can automatically perform this re-solve
    with the keyword argument prob.solve(reoptimize=True, ...).
    
  warnings.warn(INF_OR_UNB_MESSAGE)


## 10 LP Example with Alternative Optimal solutions

In [15]:
import cvxpy as cp


x = cp.Variable(2, nonneg  = True) # vector variable


obj_func=6*x[0]+3*x[1]

constraints = []
constraints.append(2*x[0]+x[1]<=16)
constraints.append(x[0]+x[1]<=10)


problem = cp.Problem(cp.Maximize(obj_func), constraints)

#problem.solve(solver=cp.CVXOPT,verbose = True)
#problem.solve(verbose = True)
problem.solve(solver=cp.GUROBI,verbose = False) # good solver plays a role

print("obj_func =")
print(obj_func.value)
print("x =")
print(x.value)

obj_func =
48.0
x =
[8. 0.]


## 11 LP Example (Algebraic)

In [16]:
import cvxpy as cp


x = cp.Variable(2, nonneg  = True) # vector variable

obj_func=x[0]+x[1]

constraints = []
constraints.append((2/3)*x[0]+x[1]<=18)
constraints.append(2*x[0]+x[1]>=8)
constraints.append(x[0]<=12)
constraints.append(x[1]<=16)

problem = cp.Problem(cp.Maximize(obj_func), constraints)

problem.solve(solver=cp.GUROBI,verbose = False)

print("obj_func =")
print(obj_func.value)
print("x =")
print(x.value)

obj_func =
22.0
x =
[12. 10.]


## 12 MIP Spacecraft

In [17]:
import cvxpy as cp

x = cp.Variable(2, integer = True)


obj_func=x[0]+x[1]

constraints = []
constraints.append(17*x[0]+32*x[1]<=136)
constraints.append(32*x[0]+15*x[1]<=120)
constraints.append(x[0]>=0)
constraints.append(x[1]>=0)


problem = cp.Problem(cp.Maximize(obj_func), constraints)

problem.solve(solver=cp.GUROBI,verbose = True)

print("obj_func =")
print(obj_func.value)
print("x =")
print(x.value)


                                     CVXPY                                     
                                     v1.2.1                                    
(CVXPY) Aug 30 11:58:28 AM: Your problem has 2 variables, 4 constraints, and 0 parameters.
(CVXPY) Aug 30 11:58:28 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Aug 30 11:58:28 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Aug 30 11:58:28 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Aug 30 11:58:28 AM: Compiling problem (target solver=GUROBI).
(CVXPY) Aug 30 11:58:28 AM: Reduction chain: FlipObjective -> CvxAttr2Constr -> Qp2SymbolicQp -

## 13 MIP Building Gas Storage

In [19]:
import cvxpy as cp

x = cp.Variable(3, boolean = True)
y = cp.Variable((3,2), nonneg = True)


obj_func = (y[0,0]+6*y[0,1]+2*y[1,0]+5*y[1,1]+3*y[2,0]+4*y[2,1])-(8*x[0]+9*x[1]+7*x[2])

constraints = []
constraints.append(y[0,0]+y[1,0]+y[2,0]==10)
constraints.append(y[0,1]+y[1,1]+y[2,1]==6)
constraints.append(y[0,0]+y[0,1]-7*x[0]<=0)
constraints.append(y[1,0]+y[1,1]-8*x[1]<=0)
constraints.append(y[2,0]+y[2,1]-9*x[2]<=0)

problem = cp.Problem(cp.Maximize(obj_func), constraints)

problem.solve(solver=cp.GUROBI, verbose = False)

print("obj_func =")
print(obj_func.value)
print("x =")
print(x.value)
print("y =")
print(y.value)


obj_func =
48.99999999999999
x =
[1. 0. 1.]
y =
[[1. 6.]
 [0. 0.]
 [9. 0.]]


## 14 MIP Electricity Production Schedule

In [20]:
import cvxpy as cp

x = cp.Variable(3, boolean = True)
p = cp.Variable(3, nonneg = True)


obj_func = (2*p[0]+5*p[1]+p[2])+(40*x[0]+50*x[1]+35*x[2])

constraints = []
constraints.append(p[0]+p[1]+p[2]==50)
constraints.append(5*x[0]-p[0]<=0)
constraints.append(p[0]-20*x[0]<=0)
constraints.append(6*x[1]-p[1]<=0)
constraints.append(p[1]-40*x[1]<=0)
constraints.append(4*x[2]-p[2]<=0)
constraints.append(p[2]-35*x[2]<=0)

problem = cp.Problem(cp.Minimize(obj_func), constraints)

problem.solve(solver=cp.GUROBI, verbose = False)

print("obj_func =")
print(obj_func.value)
print("x =")
print(x.value)
print("p =")
print(p.value)


obj_func =
140.0
x =
[1. 0. 1.]
p =
[15.  0. 35.]


## 15 MIP Oil Transmisssion Facility

In [21]:
import cvxpy as cp

x = cp.Variable(2, boolean = True)
p = cp.Variable(2, nonneg = True)
f = cp.Variable(3)


obj_func = 2*p[0]+3*p[1]-50*x[0]-55*x[1]

constraints = []
constraints.append(p[0]-f[0]-f[2]==0)
constraints.append(p[1]-f[1]+f[2]==0)
constraints.append(f[0]+f[1]==30)
constraints.append(f[2]>=-10)
constraints.append(f[2]<=10)
constraints.append(f[0]-11*x[0]<=12)
constraints.append(f[1]-12*x[1]<=11)
constraints.append(f[0]>=0)
constraints.append(f[1]>=0)



problem = cp.Problem(cp.Maximize(obj_func), constraints)

problem.solve(solver=cp.GUROBI, verbose = False)
#problem.solve()

print("obj_func =")
print(obj_func.value)
print("x =")
print(x.value)
print("p =")
print(p.value)
print("f =")
print(f.value)

obj_func =
35.0
x =
[0. 1.]
p =
[ 0. 30.]
f =
[ 10.  20. -10.]


## 16 MIP EV Charging Station

In [22]:
import cvxpy as cp

x = cp.Variable(3, boolean = True)


obj_func = 10*x[0]+12*x[1]+13*x[2]

constraints = []
constraints.append(x[0]+x[2]>=1)
constraints.append(x[1]>=1)
constraints.append(x[0]+x[1]>=1)
constraints.append(x[2]>=1)

problem = cp.Problem(cp.Minimize(obj_func), constraints)

problem.solve(solver=cp.GUROBI, verbose = False)

print("obj_func =")
print(obj_func.value)
print("x =")
print(x.value)

obj_func =
25.0
x =
[0. 1. 1.]


## 17 MIP Wind Farm

In [23]:
import cvxpy as cp

x = cp.Variable((3,3), boolean = True)


obj_func = 10*x[0,0]+12*x[0,1]+14*x[0,2]\
            +9*x[1,0]+8*x[1,1]+15*x[1,2]\
            +10*x[2,0]+5*x[2,1]+15*x[2,2]
            
constraints = []
constraints.append(x[0,0]+x[0,1]+x[0,2]==1)
constraints.append(x[1,0]+x[1,1]+x[1,2]==1)
constraints.append(x[2,0]+x[2,1]+x[2,2]==1)
constraints.append(x[0,0]+x[1,0]+x[2,0]==1)
constraints.append(x[0,1]+x[1,1]+x[2,1]==1)
constraints.append(x[0,2]+x[1,2]+x[2,2]==1)


problem = cp.Problem(cp.Minimize(obj_func), constraints)

problem.solve(solver=cp.GUROBI, verbose = False)
#problem.solve()

print("obj_func =")
print(obj_func.value)
print("x =")
print(x.value)

obj_func =
28.0
x =
[[-0. -0.  1.]
 [ 1. -0. -0.]
 [-0.  1. -0.]]


## 18 LP Dual

In [24]:
import cvxpy as cp

#x = cp.Variable(2, nonneg = True)
x = cp.Variable(2)

obj_func = 7*x[0]+12*x[1]

constraints = []
constraints.append(0.15*x[0]+0.2*x[1]<=200) # machining time
constraints.append(0.1*x[0]+0.2*x[1]<=140) # forging time
constraints.append(2.5*x[0]+4*x[1]<=3200) # raw material
constraints.append(x[0]<=900) 
constraints.append(x[1]<=600)

constraints.append(x[0]>=0)
constraints.append(x[1]>=0)


problem = cp.Problem(cp.Maximize(obj_func), constraints)

problem.solve(solver=cp.GUROBI, verbose = False)
#problem.solve()

print("obj_func =", obj_func.value)
print("x =", x.value)

# Shadow prices or dual prices
print("optimal (0.15*x[0]+0.2*x[1]<=200) dual variable", constraints[0].dual_value)
print("optimal (0.1*x[0]+0.2*x[1]<=140) dual variable", constraints[1].dual_value)
print("optimal (2.5*x[0]+4*x[1]<=3200) dual variable", constraints[2].dual_value)
print("optimal (x[0]<=900) dual variable", constraints[3].dual_value)
print("optimal (x[1]<=600) dual variable", constraints[4].dual_value)

# Reduced costs
print("reduced cost of the 1st primal variable x[0]", constraints[5].dual_value)
print("reduced cost of the 2nd primal variable x[1]", constraints[6].dual_value)

# Note that if the problem was minimization in the cacinical form, to get the reduced costs
# we had to multiply the dual values by -1.

obj_func = 9200.0
x = [800. 300.]
optimal (0.15*x[0]+0.2*x[1]<=200) dual variable -0.0
optimal (0.1*x[0]+0.2*x[1]<=140) dual variable 20.000000000000004
optimal (2.5*x[0]+4*x[1]<=3200) dual variable 1.9999999999999998
optimal (x[0]<=900) dual variable -0.0
optimal (x[1]<=600) dual variable -0.0
reduced cost of the 1st primal variable x[0] -0.0
reduced cost of the 2nd primal variable x[1] -0.0


## 19 LP Dual

In [25]:
import cvxpy as cp

x = cp.Variable(4)

obj_func = 3*x[0]+6*x[1]+5*x[2]+4*x[3]

constraints = []
constraints.append(2*x[0]+5*x[1]+3*x[2]+4*x[3]<=5300) # Lathes
constraints.append(3*x[0]+4*x[1]+6*x[2]+4*x[3]<=5300) # Machine presses
constraints.append(x[0]>=0)
constraints.append(x[1]>=0)
constraints.append(x[2]>=0)
constraints.append(x[3]>=0)


problem = cp.Problem(cp.Maximize(obj_func), constraints)

problem.solve(solver=cp.GUROBI, verbose = False)
#problem.solve()

print("obj_func =", obj_func.value)
print("x =", x.value)

# Shadow prices or dual prices
print("dual variable for (2*x[0]+5*x[1]+3*x[2]+4*x[4]<=5300) ", constraints[0].dual_value)
print("dual variable for (3*x[0]+4*x[1]+6*x[2]+4*x[4]<=5300) ", constraints[1].dual_value)

# Reduced costs
print("reduced cost of the 1st primal variable x[0] ", constraints[2].dual_value)
print("reduced cost of the 2nd primal variable x[1] ", constraints[3].dual_value)
print("reduced cost of the 2nd primal variable x[2] ", constraints[4].dual_value)
print("reduced cost of the 2nd primal variable x[3] ", constraints[5].dual_value)

# Note that if the problem was minimization in the cacinical form, to get the reduced costs
# we had to multiply the dual values by -1.

obj_func = 6814.285714285715
x = [757.14285714 757.14285714   0.           0.        ]
dual variable for (2*x[0]+5*x[1]+3*x[2]+4*x[4]<=5300)  0.857142857142857
dual variable for (3*x[0]+4*x[1]+6*x[2]+4*x[4]<=5300)  0.42857142857142866
reduced cost of the 1st primal variable x[0]  -0.0
reduced cost of the 2nd primal variable x[1]  -0.0
reduced cost of the 2nd primal variable x[2]  0.14285714285714324
reduced cost of the 2nd primal variable x[3]  1.1428571428571423
